### ISSUE TITLE
Associate panes in other sessions/windows

### ISSUE THREAD

**Issue by tommcdo** [mhinz/vim-tmuxify#12]
Associating a pane with `:TxSetPane` prompts for session and window, but seems to ignore it. It would be nice to be able to associate to an existing pane in another window.

**Comment by jebaum** [comment]
This can be closed =)

**Comment by mhinz** [comment]
@jebaum Since I'm short on time at the moment.. would you like to get full collaborator access to this plugin? Or taking it over fully?

**Comment by jebaum** [comment]
Sure, whichever is easiest. There are also a couple of features from some other tmux plugins that I'm going to add to tmuxify, but I haven't decided if they're best added to the plugin or just as suggested maps.
