### ISSUE TITLE
:TxSetPane doesn't take arguments

### ISSUE THREAD

**Issue by DanielFGray** [mhinz/vim-tmuxify#19]
I think it would be really helpful if `:TxSetPane` would accept arguments in the form of paneids like `:TxSetPane %2` or `:TxSetPane 1:1.1` rather than forcing the user to user vim's menu

**Comment by jebaum** [comment]
Should be added now, thanks for the suggestion! Let me know if there's any problems

**Comment by DanielFGray** [comment]
this seems to have totally broken defining a pane entirely now..
http://a.pomf.se/updsfp.webm

**Comment by jebaum** [comment]
I can't reproduce, running `:TxSetPane %3` for any given pane id works for me, along with any subsequent `:TxSend`. Can you give a set of steps? not sure what happened at the end of that video

**Comment by DanielFGray** [comment]
just as a follow up, i'm not sure what happened but it works great now
