### ISSUE TITLE
Easier way to integrate with an existing tmux pane

### ISSUE THREAD

**Issue by KevinSjoberg** [mhinz/vim-tmuxify#9]
I open vim. I setup a tmux-pane which Vim can talk to with `<Leader>mn` and run a command using `<Leader>mr`. I then go ahead and create a split (in Vim) and run `<Leader>mr` which result in a new tmux-pane being created unless I bind to it using `<Leader>mp` first.

Could we improve this in some way? I think it's more natural to assume that you want to talk to the current tmux-pane and that you should specify otherwise if not.

**Comment by jebaum** [comment]
Update, haven't forgotten about this, just haven't had time. Currently I have everything working but the code is ugly because I needed to actually use it, not make it pretty. Shooting for a pull request this weekend, we'll see.

**Comment by jebaum** [comment]
@KevinSjoberg as of bb3f809, you can now have a global pane shared across all vim buffers, although you'll have to make the maps yourself to add the bang, e.g.

`nnoremap <silent> <leader>mn :TxCreate!<CR>`

instead of the default

`nnoremap <silent> <leader>mn :TxCreate<CR>`

**Comment by KevinSjoberg** [comment]
@jebaum awesome! Thanks a lot for all work put into this.

**Comment by mhinz** [comment]
I concur, great work! :shipit:

**Comment by jebaum** [comment]
Thanks! After my last post I also added a `g:tmuxify_global_maps` variable that, when set to 1, will make all the default maps use a global pane, which is a little easier than redoing all the default maps with a bang.
